# .releaserc.toml
[tool.semantic_release]
version_source = "tag"
version_variable = "pyproject.toml:project.version"
branch = "main"
tag_format = "v{version}" 

# GitHub release publisher
[tool.semantic_release.publisher.github]
enabled = true
token = "env:GH_TOKEN"  # GitHub Actions secret

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_author]
name = "github-actions[bot]"
email = "github-actions[bot]@users.noreply.github.com"
